### PR TITLE
Fix highlight for warnings with error number

### LINKED ISSUE #505: Expand warning (and error?) regex to include error codes
```rust
enum MyEnum {
    one,
}

fn main() {
    match MyEnum::one {
        one => {}
        _ => {}
    }
}
```

This warning is not highlighted:

```
warning[E0170]: pattern binding `one` is named the same as one of the variants of the type `MyEnum`
 --> src/main.rs:7:9
  |
7 |         one => {},
  |         ^^^ help: to match on the variant, qualify the path: `MyEnum::one`
```

### PR DESCRIPTION
**Pull request by CYBAI**
Fix #505

| Before | After |
| ------- | ----- |
| image | image |

### CODE REVIEW

File: ui/frontend/highlighting.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export function configureRustErrors({
   reExecuteWithBacktrace,
 }) {
   Prism.languages.rust_errors = { // eslint-disable-line camelcase
-    'warning': /^warning:.*$/m,
+    'warning': /^warning(\[E\d+\])?:.*$/m,
```
Comment (shepmaster) [inline ui/frontend/highlighting.ts]: This is a great start!

Do you see a new lines down where it says `'error-explanation': /\[E\d+\]/,`? Can we follow the same pattern here to make the `[E1234]` part a link to the error guide?

Comment (CYBAI) [reply ui/frontend/highlighting.ts]: Cool! Let me try do update it! Thanks!

**Comment by shepmaster** [comment]
Thanks!
